log:
  exp_name: napoleon_0123plus_use_learned_max_z_normals
guide:
  text: "A photo of Napoleon Bonaparte, real person"
  append_direction: False
  shape_path: shapes/napoleon.obj
  use_inpainting: False
  use_blending: False
  use_zero123plus: True
  interleave_mode: False
optim:
  seed: 0
  learn_max_z_normals: True
  alpha:               -10000
