log:
  exp_name: napoleon_0123plus_get_weight_masks_for_views_vectorized
guide:
  text: "A photo of Napoleon Bonaparte, {} view"
  append_direction: True
  shape_path: shapes/napoleon.obj
  use_zero123plus: True
optim:
  seed: 3
