log:
  exp_name: napoleon
guide:
  text: "A photo of Napoleon Bonaparte, real person"
  append_direction: False
  shape_path: shapes/napoleon.obj
  sd_inpaint: False
  sd_blending: True   
  use_zero123plus: True
  interleave_mode: False

  zero123plus_inpaint:  False
  zero123plus_blending: True

  use_diff_masks: False
    # The texture before editing
optim:
  seed: 0
  learn_max_z_normals: True
  alpha:               -1
