log:
  exp_name: napoleon_0123plus_use_learned_max_z_normals
guide:
  text: "A photo of Napoleon Bonaparte, real person"
  append_direction: False
  shape_path: shapes/napoleon.obj
  use_sd_inpaint: False  
  use_sd_blending: False   
  use_zero123plus: True
  interleave_mode: False

  zero123plus_use_inpaint:  False 
  zero123plus_use_blending: False
    # The texture before editing
optim:
  seed: 0
  learn_max_z_normals: True
  alpha:               -1
