log:
  exp_name: spiderman_0123plus_weight_mask
guide:
  text: "A photo of Spiderman"
  append_direction: False
  shape_path: shapes/human.obj
  guidance_scale: 10
  use_zero123plus: True
  use_inpainting: False
  use_blending: False
optim:
  #seed: 3
  learn_max_z_normals: False