log:
  exp_name: spiderman
guide:
  text: "A photo of Spiderman"
  append_direction: False
  shape_path: shapes/human.obj
  guidance_scale: 10
  use_zero123plus: True
optim:
  # seed: 100
  learn_max_z_normals: True
  alpha: -10