log:
  exp_name: spiderman_0123plus_learn_max_z_normals
guide:
  text: "A photo of Spiderman"
  append_direction: False
  shape_path: shapes/human.obj
  guidance_scale: 10
  use_sd_inpaint: False
  use_sd_blending:   False
  use_zero123plus: True
  interleave_mode: False

  zero123plus_use_inpaint:  False 
  zero123plus_use_blending: True
optim:
  seed: 100
  learn_max_z_normals: True
  alpha:               -0.1