log:
  exp_name: spiderman_control0123
guide:
  text: "A photo of Spiderman, {} view"
  append_direction: True
  shape_path: shapes/human.obj
  guidance_scale: 10
  second_model_type: "control_zero123"

  individual_control_of_conditions: True
  guidance_scale_crossattn: 3
  guidance_scale_concat: 3
  guidance_scale_control: 1

  guess_mode: False
  # use_inpainting: False
# optim:
#   seed: 3
