log:
  exp_name: spongebob
guide:
  text: "A photo of Spongebob, {} view"
  append_direction: True
  shape_path: shapes/spongebob.obj
  guidance_scale: 7.5
  second_model_type: "control_zero123"
  guess_mode: True
  # use_inpainting: False
# optim:
#   seed: 3
